development:
  client_url: "http://localhost:8080"
  api_user_agent: "bpmbox_development/0.1 +http://localhost:3000"
production:
  client_url: "https://bpmbox.baaij.com.au"
  api_user_agent: "bpmbox/0.1 +https://api.bpmbox.baaij.com.au"
