name: Ruby
on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/ruby.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.6
      - name: Build and run tests
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        working-directory: "./api"
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3
          cp config/database.yml.github-actions config/database.yml
          bundle exec rails db:prepare
          bundle exec rails test
